"""add parent_id to document_metadata

Revision ID: 47b2823f5f59
Revises: 8f2d48135e28
Create Date: 2025-05-26 17:23:52.410556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b2823f5f59'
down_revision: Union[str, None] = '8f2d48135e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_name_parent', 'document_metadata', ['name', 'parent_id'])
    op.create_foreign_key(None, 'document_metadata', 'document_metadata', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_metadata', type_='foreignkey')
    op.drop_constraint('uq_name_parent', 'document_metadata', type_='unique')
    op.drop_column('document_metadata', 'parent_id')
    # ### end Alembic commands ###
