"""my change

Revision ID: 9dec89c08bcc
Revises: 512c3ca23e54
Create Date: 2025-05-30 07:36:01.640792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dec89c08bcc'
down_revision: Union[str, None] = '512c3ca23e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('document_metadata', sa.Column('is_starred', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('document_metadata', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_metadata', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('document_metadata', 'is_starred')
    op.drop_column('document_metadata', 'is_archived')
    # ### end Alembic commands ###
