"""add type column to document_metadata

Revision ID: e750bbb151f2
Revises: 2a02384ab925
Create Date: 2025-05-23 10:24:08.077990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e750bbb151f2'
down_revision: Union[str, None] = '2a02384ab925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('type', sa.String(), nullable=True))
    op.alter_column('document_metadata', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'share_url', ['url_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share_url', type_='unique')
    op.alter_column('document_metadata', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('document_metadata', 'type')
    # ### end Alembic commands ###
